name: PHPUnit

on:
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'phpunit*'
      - '.github/workflows/phpunit.yml'

  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'phpunit*'
      - '.github/workflows/phpunit.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} / CI4 ${{ matrix.ci4 }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            ci4: '4.6.5'

          - php: '8.2'
            ci4: '4.7.4'

          - php: '8.3'
            ci4: '4.7.4'

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - name: Require CodeIgniter ${{ matrix.ci4 }}
        run: composer require --dev codeigniter4/framework:${{ matrix.ci4 }} --no-update

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: PHPUnit
        run: vendor/bin/phpunit
